Repository Another-Glass/Assignment1_Team1, pull requests merged in 2021-11, with the labels that each got.

#1 [Chore]: 깃허브 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/-method--feature-request.md
Labels: ⭐️ Chore, 🧑🏻‍💻 상수

#10 [chore]: 개발 환경 셋팅
  src/.babelrc
  src/.eslintrc.json
  src/.gitignore
  src/.prettierrc.json
  src/app.js
  src/bin/www
  src/package.json
  src/views/error.jade
  src/views/index.jade
  src/views/layout.jade
Labels: ⭐️ Chore, 🧑🏻‍💻 1주차 팀

#11 [Feat]: 사용자 회원가입 로직 구성
  .github/ISSUE_TEMPLATE/-method--feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  src/app.js
  src/config/db.js
  src/config/secretKey.js
  src/controllers/userController.js
  src/global/routes.js
  src/lib/encryption.js
  src/models/userModel.js
  src/package.json
  src/routes/globalRouter.js
  src/routes/userRouter.js
  src/service/userService.js
  src/utils/db/index.js
  src/utils/responseMessage.js
  src/utils/statusCode.js
  src/utils/util.js
Labels: 🔥 Feat, 🧑🏻‍💻 1주차 팀

#12 [Feat]: 개발 환경 셋팅
  src/.babelrc
  src/.eslintrc.json
  src/.gitignore
  src/.prettierrc.json
  src/app.js
  src/bin/www
  src/config/db.js
  src/config/secretKey.js
  src/controllers/userController.js
  src/global/routes.js
  src/lib/encryption.js
  src/models/userModel.js
  src/package.json
  src/routes/globalRouter.js
  src/routes/userRouter.js
  src/service/userService.js
  src/utils/db/index.js
  src/utils/responseMessage.js
  src/utils/statusCode.js
  src/utils/util.js
  src/views/error.jade
  src/views/index.jade
  src/views/layout.jade
Labels: 🔥 Feat, 🧑🏻‍💻 1주차 팀

#13 [feat]: 사용자 로그인 로직 구성
  src/controllers/userController.js
  src/global/routes.js
  src/lib/jwt.js
  src/routes/userRouter.js
  src/service/userService.js
Labels: 🔥 Feat, 🧑🏻‍💻 1주차 팀

#14 [feat]: 게시판 게시글 생성
  src/app.js
  src/controllers/postController.js
  src/middlewares/auth.js
  src/models/postModel.js
  src/routes/postRouter.js
  src/service/postService.js
Labels: 🔥 Feat, 🧑🏻‍💻 1주차 팀

#15 [feat]: 게시판 게시글 상세 조회
  src/controllers/postController.js
  src/routes/postRouter.js
  src/service/postService.js
Labels: 🔥 Feat, 🧑🏻‍💻 1주차 팀

#16 [feat]: 게시판 게시글 삭제
  src/controllers/postController.js
  src/routes/postRouter.js
  src/service/postService.js
Labels: 🔥 Feat, 🧑🏻‍💻 1주차 팀

#17 [feat]: 게시판 게시글 수정
  src/controllers/postController.js
  src/routes/postRouter.js
  src/service/postService.js
Labels: 🔥 Feat, 🧑🏻‍💻 1주차 팀

#18 [feat]: 게시판 게시글 목록 조회
  src/controllers/postController.js
  src/routes/postRouter.js
  src/service/postService.js
Labels: 🔥 Feat, 🧑🏻‍💻 1주차 팀

#19 [fix]: MongoDB URI 설정 완료
  src/config/db.js
  src/config/secretKey.js
  src/utils/db/index.js
Labels: 🐞 bug, 🧑🏻‍💻 1주차 팀

#20 [fix]: 유저 회원가입 및 유저 로그인 DB 설정
  src/controllers/userController.js
  src/service/userService.js
Labels: 🐞 bug, 🧑🏻‍💻 1주차 팀

#21 [feat]: 게시글 생성 API DB 설정
  src/controllers/postController.js
  src/models/postModel.js
Labels: 🧑🏻‍💻 1주차 팀, 🛠 Fix

#22 [fix]: 게시글 수정 API DB 설정
  src/controllers/postController.js
  src/service/postService.js
Labels: 🧑🏻‍💻 1주차 팀, 🛠 Fix

#24 [fix]: 게시글 api 버그수정 및 예외처리 추가
  src/controllers/postController.js
  src/utils/responseMessage.js
Labels: 🧑🏻‍💻 1주차 팀, 🛠 Fix

#25 [feat]: 게시판 검색 조회
  src/controllers/postController.js
  src/global/routes.js
  src/routes/postRouter.js
  src/service/postService.js
Labels: 🔥 Feat, 🧑🏻‍💻 1주차 팀

#31 [feat] 게시글 조회수 증가 설정
  src/controllers/postController.js
  src/middlewares/auth.js
  src/routes/postRouter.js
  src/service/postService.js
Labels: 🔥 Feat, 🧑🏻‍💻 1주차 팀

#32 [feat]: 댓글, 대댓글 구현, 로그인버그 수정
  src/controllers/commentController.js
  src/global/routes.js
  src/models/commentModel.js
  src/models/postModel.js
  src/models/userModel.js
  src/routes/postRouter.js
  src/service/commentService.js
  src/service/userService.js
  src/utils/responseMessage.js
Labels: 🔥 Feat, 🧑🏻‍💻 1주차 팀

#33 [feat]: README 1차 정리
  README.md
Labels: 📕 documentation, 🧑🏻‍💻 상수

#36 [fix]: 생성 시 응답 변경, README 수정
  1weak-1st.postman_collection.json
  README.md
  src/controllers/commentController.js
  src/controllers/postController.js
Labels: 🧑🏻‍💻 1주차 팀, 🛠 Fix

#37 [docs]: 오탈자 수정
  README.md
  src/ecosystem.config.js
Labels: 🔥 Feat, 🧑🏻‍💻 1주차 팀

#38 [style]:주석 추가 및 정리
  src/app.js
  src/bin/www
  src/controllers/commentController.js
  src/controllers/postController.js
  src/controllers/userController.js
  src/global/routes.js
  src/routes/globalRouter.js
  src/routes/postRouter.js
  src/routes/userRouter.js
  src/service/commentService.js
  src/views/error.jade
  src/views/index.jade
  src/views/layout.jade
Labels: 🧑🏻‍💻 1주차 팀, 🛠 Fix
